# Generated by Django 5.2.8 on 2026-02-25 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Question",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.CharField(max_length=255)),
                (
                    "type",
                    models.CharField(
                        choices=[("mcq", "Multiple Choice"), ("text", "Text Answer")],
                        default="text",
                        max_length=10,
                    ),
                ),
                ("answer_text", models.CharField(blank=True, max_length=255)),
                ("option_a", models.CharField(blank=True, max_length=255)),
                ("option_b", models.CharField(blank=True, max_length=255)),
                ("option_c", models.CharField(blank=True, max_length=255)),
                ("option_d", models.CharField(blank=True, max_length=255)),
                ("correct_option", models.CharField(blank=True, max_length=1)),
                (
                    "question_image",
                    models.ImageField(
                        blank=True, null=True, upload_to="quiz/question_images/"
                    ),
                ),
                (
                    "question_audio",
                    models.FileField(
                        blank=True, null=True, upload_to="quiz/question_audio/"
                    ),
                ),
                (
                    "question_video",
                    models.FileField(
                        blank=True, null=True, upload_to="quiz/question_videos/"
                    ),
                ),
                (
                    "answer_image",
                    models.ImageField(
                        blank=True, null=True, upload_to="quiz/answer_images/"
                    ),
                ),
                (
                    "answer_audio",
                    models.FileField(
                        blank=True, null=True, upload_to="quiz/answer_audio/"
                    ),
                ),
                (
                    "answer_video",
                    models.FileField(
                        blank=True, null=True, upload_to="quiz/answer_videos/"
                    ),
                ),
            ],
        ),
    ]
